const POSTS_KEY="maeum-feed-posts",THEME_KEY="maeum-feed-theme",REACTIONS=["💪","❤️","👏"],AVATAR_COLORS=["#e8d9b7","#cddcc6","#d6d2e5","#e7c9c2","#c9dce2"],MAX_IMAGE_BYTES=10*1024*1024,MAX_STORED_IMAGE_BYTES=1.5*1024*1024,DAILY_START="2026-06-10";
const samplePosts=[
{id:"sample-1",author:"Slow Steps",text:"Some days, simply making it through is more than enough, even when it feels like you accomplished nothing.",createdAt:Date.now()-1080000,reactions:{"💪":12,"❤️":24,"👏":7},reacted:[]},
{id:"sample-2",author:"Here & Now",text:"No comparisons today. I only want to take one small step beyond where I was yesterday.",createdAt:Date.now()-10800000,reactions:{"💪":18,"❤️":9,"👏":11},reacted:["💪"]},
{id:"sample-3",author:"A Little Courage",text:"Here are the words I once needed to hear: you are already doing better than you think.",createdAt:Date.now()-86400000,reactions:{"💪":8,"❤️":31,"👏":5},reacted:[]}
];
const dailyQuotes=[
{text:"The best kind of revenge is, not to become like unto them.",author:"Marcus Aurelius",source:"Meditations, Book VI",url:"https://www.gutenberg.org/files/2680/2680-h/2680-h.htm#link2H_4_0008"},
{text:"Men are disturbed not by the things which happen, but by the opinions about the things.",author:"Epictetus",source:"Encheiridion, V",url:"https://www.gutenberg.org/files/10661/10661-h/10661-h.htm"},
{text:"Nothing can bring you peace but yourself.",author:"Ralph Waldo Emerson",source:"Essays: First Series, Self-Reliance",url:"https://www.gutenberg.org/files/16643/16643-h/16643-h.htm"},
{text:"Trust thyself: every heart vibrates to that iron string.",author:"Ralph Waldo Emerson",source:"Essays: First Series, Self-Reliance",url:"https://www.gutenberg.org/files/2944/2944-h/2944-h.htm"},
{text:"It is never too late to give up our prejudices.",author:"Henry David Thoreau",source:"Walden",url:"https://www.gutenberg.org/files/205/205-h/205-h.htm"},
{text:"Tomorrow is a new day with no mistakes in it yet.",author:"L. M. Montgomery",source:"Anne of Green Gables",url:"https://www.gutenberg.org/files/45/45-h/45-h.htm"},
{text:"Goodness is the only investment that never fails.",author:"Henry David Thoreau",source:"Walden",url:"https://www.gutenberg.org/files/205/205-h/205-h.htm"},
{text:"Success is to be measured by the obstacles which he has overcome while trying to succeed.",author:"Booker T. Washington",source:"Up from Slavery",url:"https://www.gutenberg.org/files/2376/2376-h/2376-h.htm"},
{text:"Make it not any longer a matter of dispute what are the signs of a good man, but really and actually to be such.",author:"Marcus Aurelius",source:"Meditations, Book X",url:"https://www.gutenberg.org/files/2680/2680-h/2680-h.htm"}
];
const $=selector=>document.querySelector(selector),elements={root:document.documentElement,themeColor:$("meta[name='theme-color']"),themeToggle:$("#theme-toggle"),form:$("#post-form"),textarea:$("#post-text"),imageInput:$("#image-input"),imagePreview:$("#image-preview"),previewImage:$("#preview-image"),removeImage:$("#remove-image"),submit:$(".submit-button"),characterCount:$("#character-count"),postCount:$("#post-count"),feed:$("#feed"),emptyState:$("#empty-state"),template:$("#post-template"),toast:$("#toast")};
let posts=loadPosts(),toastTimer,selectedImage="",imageProcessing=null;
function loadPosts(){try{const stored=JSON.parse(localStorage.getItem(POSTS_KEY));if(!Array.isArray(stored))return samplePosts;const samples=new Map(samplePosts.map(post=>[post.id,post]));return stored.map(post=>samples.has(post.id)?{...post,author:samples.get(post.id).author,text:samples.get(post.id).text}:post)}catch{return samplePosts}}
function savePosts(){try{localStorage.setItem(POSTS_KEY,JSON.stringify(posts));return true}catch{return false}}
function dateKey(date){return date.toISOString().slice(0,10)}
function ensureDailyQuotes(){const start=new Date(`${DAILY_START}T12:00:00Z`),today=new Date(`${dateKey(new Date())}T12:00:00Z`),existing=new Set(posts.map(post=>post.id));for(let date=start,index=0;date<=today;date=new Date(date.getTime()+86400000),index++){const key=dateKey(date),id=`daily-${key}`;if(existing.has(id))continue;const quote=dailyQuotes[index%dailyQuotes.length];posts.push({id,author:quote.author,text:quote.text,source:quote.source,sourceUrl:quote.url,official:true,createdAt:Date.parse(`${key}T12:00:00Z`),reactions:Object.fromEntries(REACTIONS.map(emoji=>[emoji,0])),reacted:[]})}savePosts()}
function getInitialTheme(){const stored=localStorage.getItem(THEME_KEY);if(stored==="light"||stored==="dark")return stored;return matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"}
function setTheme(theme){const dark=theme==="dark";elements.root.dataset.theme=theme;elements.themeToggle.setAttribute("aria-label",`Switch to ${dark?"light":"dark"} mode`);elements.themeColor.content=dark?"#111210":"#f7f7f5";localStorage.setItem(THEME_KEY,theme)}
function formatTime(timestamp){const minutes=Math.floor(Math.max(0,Date.now()-timestamp)/60000),hours=Math.floor(minutes/60),days=Math.floor(hours/24);if(minutes<1)return"Just now";if(minutes<60)return`${minutes}m ago`;if(hours<24)return`${hours}h ago`;if(days<7)return`${days}d ago`;return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(timestamp)}
function getAuthor(){const names=["Kind Heart","One Step","Here & Now","A Little Courage"];return names[Math.floor(Math.random()*names.length)]}
function notify(message){clearTimeout(toastTimer);elements.toast.textContent=message;elements.toast.classList.add("show");toastTimer=setTimeout(()=>elements.toast.classList.remove("show"),2200)}
function createReactionButton(post,emoji){const button=document.createElement("button"),count=post.reactions?.[emoji]||0,active=post.reacted?.includes(emoji);button.type="button";button.className=`reaction-button${active?" active":""}`;button.dataset.action="react";button.dataset.emoji=emoji;button.setAttribute("aria-pressed",String(Boolean(active)));button.setAttribute("aria-label",`${emoji}, ${count} reactions`);button.append(emoji);const countElement=document.createElement("span");countElement.textContent=count;button.append(countElement);return button}
function createPostElement(post,index){const fragment=elements.template.content.cloneNode(true),article=fragment.querySelector(".post"),avatar=fragment.querySelector(".post-avatar"),text=fragment.querySelector(".post-text"),image=fragment.querySelector(".post-image"),source=fragment.querySelector(".post-source"),deleteButton=fragment.querySelector(".delete-button");article.dataset.id=post.id;article.classList.toggle("official",Boolean(post.official));avatar.textContent=post.author.slice(0,1);avatar.style.backgroundColor=AVATAR_COLORS[index%AVATAR_COLORS.length];fragment.querySelector(".post-author").textContent=post.author;const time=fragment.querySelector(".post-time");time.textContent=formatTime(post.createdAt);time.dateTime=new Date(post.createdAt).toISOString();text.textContent=post.text;text.hidden=!post.text;if(post.image){image.src=post.image;image.hidden=false}if(post.source&&post.sourceUrl){source.textContent=`Source: ${post.source}`;source.href=post.sourceUrl;source.hidden=false}deleteButton.hidden=Boolean(post.official);const reactions=fragment.querySelector(".reactions");REACTIONS.forEach(emoji=>reactions.append(createReactionButton(post,emoji)));return fragment}
function render(){const sorted=[...posts].sort((a,b)=>b.createdAt-a.createdAt);elements.feed.replaceChildren(...sorted.map(createPostElement));elements.postCount.textContent=`${posts.length} ${posts.length===1?"post":"posts"}`;elements.feed.hidden=!posts.length;elements.emptyState.hidden=Boolean(posts.length)}
function addPost(text,image){const post={id:crypto.randomUUID(),author:getAuthor(),text,image,createdAt:Date.now(),reactions:Object.fromEntries(REACTIONS.map(emoji=>[emoji,0])),reacted:[]};posts.push(post);if(savePosts()){render();return true}posts=posts.filter(item=>item.id!==post.id);return false}
function toggleReaction(post,emoji){post.reactions||={};post.reacted||=[];const active=post.reacted.includes(emoji);post.reactions[emoji]=Math.max(0,(post.reactions[emoji]||0)+(active?-1:1));post.reacted=active?post.reacted.filter(item=>item!==emoji):[...post.reacted,emoji];savePosts();render()}
function clearSelectedImage(){selectedImage="";imageProcessing=null;elements.imageInput.value="";elements.previewImage.removeAttribute("src");elements.imagePreview.hidden=true}
function loadImage(file){return new Promise((resolve,reject)=>{const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{URL.revokeObjectURL(url);resolve(image)};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("Unsupported image"))};image.src=url})}
async function compressImage(file){if(!file.type.startsWith("image/")||file.size>MAX_IMAGE_BYTES)throw new Error("Choose an image smaller than 10 MB.");const image=await loadImage(file),scale=Math.min(1,1200/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);const data=canvas.toDataURL("image/webp",.76);if(data.length>MAX_STORED_IMAGE_BYTES)throw new Error("This image is too detailed. Please choose a smaller one.");return data}
ensureDailyQuotes();setTheme(getInitialTheme());render();
elements.themeToggle.addEventListener("click",()=>setTheme(elements.root.dataset.theme==="dark"?"light":"dark"));
elements.textarea.addEventListener("input",()=>elements.characterCount.textContent=elements.textarea.value.length);
elements.imageInput.addEventListener("change",()=>{const file=elements.imageInput.files[0];if(!file)return;elements.submit.disabled=true;imageProcessing=compressImage(file).then(data=>{selectedImage=data;elements.previewImage.src=data;elements.imagePreview.hidden=false}).catch(error=>{clearSelectedImage();notify(error.message)}).finally(()=>{elements.submit.disabled=false});});
elements.removeImage.addEventListener("click",clearSelectedImage);
elements.form.addEventListener("submit",async event=>{event.preventDefault();if(imageProcessing)await imageProcessing;const text=elements.textarea.value.trim();if(!text&&!selectedImage){notify("Write something or add an image first.");return}if(!addPost(text,selectedImage)){notify("Browser storage is full. Remove an older image post and try again.");return}elements.form.reset();elements.characterCount.textContent="0";clearSelectedImage();notify("Your post has been shared.")});
elements.feed.addEventListener("click",event=>{const button=event.target.closest("button[data-action]");if(!button)return;const post=posts.find(item=>item.id===button.closest(".post").dataset.id);if(!post)return;if(button.dataset.action==="react")toggleReaction(post,button.dataset.emoji);if(button.dataset.action==="delete"&&!post.official&&confirm("Delete this post?")){posts=posts.filter(item=>item.id!==post.id);savePosts();render();notify("Post deleted.")}});
